[[Xorg_libXcursor]]
arch = "aarch64"
git-tree-sha1 = "1c7b99743540ff80b26d29eb5d4f012252b337d4"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "91a58931b3265d5efb6b545f15a2500cd65792fc2f62e42208a868f240529993"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.aarch64-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "aarch64"
git-tree-sha1 = "720adbbff27a79da31d6aeb29ac6a8d129d04284"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "1b580f3fb4167be018ff87f01259f3a6c45ffd356cb8936883d03462ed73f449"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.aarch64-linux-musl.tar.gz"
[[Xorg_libXcursor]]
arch = "aarch64"
git-tree-sha1 = "dde292f36a19407bf93239dc54cde1cecde07c9d"
os = "freebsd"

    [[Xorg_libXcursor.download]]
    sha256 = "3473c13bdee8e86b7f49d6919c9b8c85437ee77d429f10f3c9cadd1d1551ba6f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXcursor]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f25c8964ad8f907739ce636574bcd700979886c"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "d51ddc7a81777abb106d394e589ba3fe0ddd3ed18c29475bf8686065c2f72b36"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXcursor]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f9ec051bedcf5a3914306ece0ff58593ec996977"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "282e7093449b70c02b98798f24919c48e4ef75722dd709b40f4fba077d74e105"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXcursor]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f0759c41266406d7c3326e8f2ac7c08fc96f43a"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "cea72a3dccb5df1e622e131323108c92de791003af8cdbfe078677b7c70544ab"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXcursor]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "78983901fd258c6f95fcb9f67946600c7e7fdde1"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "5d63b2efe17fd512e1eb8e75ac5fcd7b498e51807795c6c8e67dc55d65528a69"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXcursor]]
arch = "i686"
git-tree-sha1 = "a7282fffee2593e400c7a15ae02bff1f417fe4ad"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "dcb9f2fdf4e8d697bcae4589c55d2c7e747e6f58db7cb1e1236d66692d549ab6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.i686-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "i686"
git-tree-sha1 = "c83f29c0c80b8478014dd693b26a33d380148b5a"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "af2869270f26d5e834cd9871bd2780dbcabc3009f738764ac0883b220d5ebf70"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.i686-linux-musl.tar.gz"
[[Xorg_libXcursor]]
arch = "powerpc64le"
git-tree-sha1 = "20838cfd8b08134bcd3890048545ea78d388631a"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "1f39d975a09bc555d27c91169485c3c284daffc3f5b58dcab8124590b2195cef"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "riscv64"
git-tree-sha1 = "9187192f14386ad43cabbf5a4285e659de437057"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "31cc248863425aa0938c2453bf1b5039aa6b10fc197b5e78591caee7c0f77989"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.riscv64-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "x86_64"
git-tree-sha1 = "353f5c4e091a41ba8da5297d1b4d13652aa7f775"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "64ed42914b4ee0fd87e65bebe150f8a98968e184879d0f1932f4e35fe7c0c700"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.x86_64-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "x86_64"
git-tree-sha1 = "094637e0686a21d59415b9e3d7b558a60095186b"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "3f1613ab5a878de8b33b33689eb470ee5c8bd3333de03a0a804db3f6a3ad275d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.x86_64-linux-musl.tar.gz"
[[Xorg_libXcursor]]
arch = "x86_64"
git-tree-sha1 = "115d2eb2832510f4ae114e366bfe031c59f10271"
os = "freebsd"

    [[Xorg_libXcursor.download]]
    sha256 = "d637e61741ab6f83fff3785002e7f5287d173ef3e9df42f79679b0929f64368c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.4+0/Xorg_libXcursor.v1.2.4.x86_64-unknown-freebsd.tar.gz"
