[[Xorg_libXcursor]]
arch = "aarch64"
git-tree-sha1 = "78fc19e9d0fcf9468baf39ca5404be01621b5b8d"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "4948344c7b35330ec9143584e215ba83e21c17e7a670072ffa323fd18bbcdc84"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.aarch64-linux-musl.tar.gz"
[[Xorg_libXcursor]]
arch = "aarch64"
git-tree-sha1 = "913770b7e4b3aa3a17c068ce1396efbc39ecb01b"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "363b82c114b6c2547e007c3499a7a5a8aa25a3a96b1e9f3e76d32f9328a18219"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.aarch64-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "x86_64"
git-tree-sha1 = "9d1b7e42dfdb0b3ba2d0f81701ee609bad9b880e"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "499f324bb5e19a65e10a5d5c7028b48be5dab751b8a6d694c9d12826724ef897"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.x86_64-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "powerpc64le"
git-tree-sha1 = "433036445af11a37fa04076bf5798801d52dc9e2"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "53680c1793824dfc4f3e7c5a8f1ee2432549ce5fdf8cbde6828f5c1a76d3e921"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "x86_64"
git-tree-sha1 = "401409970af94a3457f14e2853d169e1c90b1c49"
os = "freebsd"

    [[Xorg_libXcursor.download]]
    sha256 = "8068920e3597d4bbd2aa6471894774769a3493f73cd1b76f1f77bbfa77c5b869"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXcursor]]
arch = "i686"
git-tree-sha1 = "97c216960e15595bec68e9b8bd26df29baa9bb2a"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "37526ab23d3ae2f9f3c777602086e158651c4d4e3d1b3244cd78b72801945697"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.i686-linux-gnu.tar.gz"
[[Xorg_libXcursor]]
arch = "i686"
git-tree-sha1 = "cf9616c48beb53bdd4effae0ec96a78fb6b709ce"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "80a1c3044ad15ca4f1994c29ad8c67d28cec56c02295aac1fdfbaec2c0c7e871"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.i686-linux-musl.tar.gz"
[[Xorg_libXcursor]]
arch = "armv7l"
git-tree-sha1 = "cd7ce0e85c2af18828733a29280b48614701b474"
libc = "glibc"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "7457b0cbf60e3af394ec4947dc9d1fa97d7a4ba8ce44a45a06d80b9eae9ec72e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXcursor]]
arch = "x86_64"
git-tree-sha1 = "4fa3b82462ec3c08ec8aa0ae9152c999a5776dd1"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "2d7ee876e2e5cfde7fad7175ce07098a6c3bde8acaa11d916d636e860072cc86"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.x86_64-linux-musl.tar.gz"
[[Xorg_libXcursor]]
arch = "armv7l"
git-tree-sha1 = "6d24b568cae54a21dd44709c1a7c9541aaeba009"
libc = "musl"
os = "linux"

    [[Xorg_libXcursor.download]]
    sha256 = "a071ed08b1a3965b829a933b40c0fdeba2c56175c8053dbf914d0c7f41c310a3"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXcursor_jll.jl/releases/download/Xorg_libXcursor-v1.2.0+1/Xorg_libXcursor.v1.2.0.armv7l-linux-musleabihf.tar.gz"
